# MT5 Configuration
mt5:
  # These can be overridden by environment variables:
  #   MT5_LOGIN, MT5_PASSWORD, MT5_SERVER, MT5_PATH
  login: 0 # (override via MT5_LOGIN)
  password: "" # (override via MT5_PASSWORD)
  server: "" # (override via MT5_SERVER)
  # path: ""         # (override via MT5_PATH) let MT5 auto-detect if empty

# Trading Symbols
symbols:
  - XAUUSD.s # Vàng
  - EURUSD.s # Euro/USD
  - GBPUSD.s # Bảng Anh/USD
  # - USDJPY.s   # USD/Yên Nhật
  # - AUDUSD.s   # Đô Úc/USD

# Timeframes to scan (in MT5 format)
timeframes:
  - M15 # 15 phút
  - H1 # 1 giờ
  - H4 # 4 giờ
  - D1 # 1 ngày

# Telegram Configuration
telegram:
  # These can be overridden by environment variables:
  #   TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID
  bot_token: "" # (override via TELEGRAM_BOT_TOKEN)
  chat_id: "" # (override via TELEGRAM_CHAT_ID)
  send_charts: true # Send charts with alerts (requires matplotlib)

# Pattern Detection Settings
patterns:
  enabled:
    - bullish_engulfing # Nến nhấn chìm tăng
    - bearish_engulfing # Nến nhấn chìm giảm
    - hammer # Búa
    - shooting_star # Sao băng
    - doji # Doji

  # Pattern specific settings
  doji_threshold: 0.1 # 10% body/range ratio for doji (unchanged)
  min_strength: 0.6 # Tăng lên 60% để giảm tín hiệu nhiễu
  min_enhanced_strength: 0.4 # Ngưỡng tối thiểu cho enhanced patterns

  # NOTE: hammer_shadow_ratio and shooting_star_shadow_ratio removed
  # Algorithm now uses fixed 25% body threshold and 10% shadow limits

# Enhanced Analysis Settings (NEW)
analysis:
  # Enable enhanced pattern detection with context
  enable_enhanced_mode: true

  # Trend Analysis
  trend:
    ema_short_period: 20
    ema_long_period: 50
    trend_strength_threshold: 0.0001 # 0.01%
    sideways_threshold: 0.0005 # 0.05%

  # Support/Resistance Analysis
  support_resistance:
    sr_lookback_periods: 20
    sr_min_touches: 2
    sr_proximity_threshold: 0.001 # 0.1%

  # Context Filtering
  enable_trend_filtering: true
  enable_sr_filtering: true
  allow_reversal_patterns: true
  reversal_pattern_names:
    - hammer
    - shooting_star
    - bullish_engulfing
    - bearish_engulfing

# System Settings
system:
  scan_interval: 60 # Quét mỗi 60 giây
  alert_cooldown: 3600 # 1 giờ cooldown cho cùng một tín hiệu
  log_level: INFO
  timezone: "Asia/Ho_Chi_Minh" # Múi giờ Việt Nam

  # Cache settings
  cache_alerts: true
  cache_expiry: 7200 # 2 giờ

# Risk Management (optional for future enhancement)
risk:
  max_alerts_per_hour: 20
  quiet_hours:
    enabled: true
    start: "23:00" # Không gửi alert từ 23h
    end: "06:00" # đến 6h sáng
